<h1><?= $dataset->title ?></h1>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <?= $this->partial('mkdf/datasets/partial/dataset-features', ['features' => $features, 'dataset_id' => $dataset->id] ) ?>
        </div>
        <div class="col-md-9">
            <h2>Dataset files</h2>
            <?= $this->partial('mkdf/core/partial/actions', $actions); ?>
            <!--
            UUID: <?= $dataset->uuid ?><br />
            -->
            <?php if ($can_view):?>
                <table class="table table-bordered">
                    <tr class="table-active">

                        <th>Title</th>
                        <th>Description</th>
                        <th>Filename</th>
                        <th>Type</th>
                        <th>Size</th>
                        <th>Actions</th>


                    </tr>
                    <?php foreach ($files as $f) : ?>
                        <tr>
                            <td><?= $this->escapeHtml($f['title']) ?></td>
                            <td><?= $this->escapeHtml($f['description']) ?></td>
                            <td><?= $this->escapeHtml($f['filename_original']) ?></td>
                            <td><?= $this->escapeHtml($f['file_type']) ?></td>
                            <td><?= $this->escapeHtml($f['file_size_str']) ?></td>
                            <td class="text-nowrap">
                                <?php
                                if ($can_read) {
                                    $downloadFileAction = [
                                        'class'=>'btn-group-sm',
                                        'buttons'=>[
                                            ['type'=>'primary','label'=>'', 'icon' => 'download', 'target'=> 'file', 'params'=> ['id' => $f['id'], 'action' => 'download']],
                                        ]
                                    ];
                                    print($this->partial('mkdf/core/partial/actions', $downloadFileAction));
                                }
                                if ($can_edit) {
                                    $deleteFileAction = [
                                        'class'=>'btn-group-sm',
                                        'buttons'=>[
                                            ['type'=>'danger','label'=>'', 'icon' => 'delete', 'target'=> 'file', 'params'=> ['id' => $f['id'], 'action' => 'delete-confirm']],
                                        ]
                                    ];
                                    print($this->partial('mkdf/core/partial/actions', $deleteFileAction));
                                }

                                ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>

                </table>
            <?php endif; ?>

        </div>
    </div>
</div>