<h1><?= $dataset->title ?></h1>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <?= $this->partial('mkdf/datasets/partial/dataset-features', ['features' => $features, 'dataset_id' => $dataset->id] ) ?>
        </div>
        <div class="col-md-9">
            <h2>Dataset files</h2>
            <?= $this->partial('mkdf/core/partial/actions', $actions); ?>
            <!--
            UUID: <?= $dataset->uuid ?><br />
            -->

            <form id="sparqlForm">
                <div class="row">
                    <div class="col-md-12"><label for="queryKey">Select a key to use for interacting with these files</label><br /></div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">

                        <select class="custom-select custom-select-sm" id="queryKey">
                            <?php
                            foreach ($keys as $key) {
                                echo ("<option value='".$key['keyUUID']."'>".$key['keyName']." [".$key['keyUUID']."]</option>");
                            }
                            ?>
                        </select>
                    </div>
                </div>
            </form>

            <?php if ($can_view):?>
                <table class="table table-bordered">
                    <tr class="table-active">

                        <th>Title</th>
                        <th>Description</th>
                        <th>Filename</th>
                        <th>Type</th>
                        <th>Size</th>
                        <th>Actions</th>


                    </tr>
                    <?php foreach ($files as $f) : ?>
                        <tr>
                            <td><?= $this->escapeHtml($f['title']) ?></td>
                            <td><?= $this->escapeHtml($f['description']) ?></td>
                            <td><?= $this->escapeHtml($f['filenameOriginal']) ?></td>
                            <td><?= $this->escapeHtml($f['type']) ?></td>
                            <td><?= $this->escapeHtml($f['sizeStr']) ?></td>
                            <td class="text-nowrap">
                                <?php
                                if ($can_read) {
                                    $downloadFileAction = [
                                        'class'=>'btn-group-sm',
                                        'buttons'=>[
                                            ['type'=>'primary','label'=>'', 'icon' => 'download', 'target'=> 'file', 'params'=> ['id' => $f['filename'], 'action' => 'download']],
                                        ]
                                    ];
                                    print($this->partial('mkdf/core/partial/actions', $downloadFileAction));
                                }
                                if ($can_edit) {
                                    $deleteFileAction = [
                                        'class'=>'btn-group-sm',
                                        'buttons'=>[
                                            ['type'=>'danger','label'=>'', 'icon' => 'delete', 'target'=> 'file', 'params'=> ['id' => $f['filename'], 'action' => 'delete-confirm']],
                                        ]
                                    ];
                                    print($this->partial('mkdf/core/partial/actions', $deleteFileAction));
                                }

                                ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>

                </table>
            <?php endif; ?>

        </div>
    </div>
</div>