<h1><?= $dataset->title ?></h1>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <?= $this->partial('mkdf/datasets/partial/dataset-features', ['features' => $features, 'dataset_id' => $dataset->id] ) ?>
        </div>
        <div class="col-md-9">
            <h2>Dataset files</h2>
            <?= $this->partial('mkdf/core/partial/actions', $actions); ?>
            <!--
            UUID: <?= $dataset->uuid ?><br />
            -->
            <?php if ($can_read):?>
                <table class="table table-striped table-bordered">
                    <tr>

                        <th>Title</th>
                        <th>Description</th>
                        <th>Filename</th>
                        <th>Type</th>
                        <th>Size</th>
                        <th></th>


                    </tr>
                    <?php foreach ($files as $f) : ?>
                        <tr>
                            <td><?= $this->escapeHtml($f['title']) ?></td>
                            <td><?= $this->escapeHtml($f['description']) ?></td>
                            <td><?= $this->escapeHtml($f['filename_original']) ?></td>
                            <td><?= $this->escapeHtml($f['file_type']) ?></td>
                            <td><?= $this->escapeHtml($f['file_size']) ?></td>
                            <td><a href="<?= $this->url('file', ['action' => 'download', 'id' => $f['id']]) ?>"><i class="fas fa-download"></i></a></td>
                        </tr>
                    <?php endforeach; ?>

                </table>
            <? endif; ?>

        </div>
    </div>
</div>